<?php

namespace SharkBowlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends EntityRepository
{
}
